server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "golang-app"
    static_configs:
      - targets:
          - localhost
        labels:
          app: golang-app
          __path__: /var/log/*.log
    pipeline_stages:
      - json:
          expressions:
            app_name: app_name
            file: file
            func: func
            level: level
            msg: msg
            time: time
      - labels:
          app_name:
          file:
          func:
          level:
          msg:
          time:
